# Generated by Django 5.2.5 on 2025-08-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('categoria_cnh', models.CharField(max_length=5)),
                ('data_validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('renavam', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('chassi', models.CharField(max_length=50, unique=True)),
                ('tipo_modelo', models.CharField(choices=[('HATCH', 'Hatch'), ('SEDAN', 'Sedã'), ('SUV', 'SUV'), ('CROSSOVER', 'Crossover'), ('COUPE', 'Coupé'), ('CONVERSIVEL', 'Conversível'), ('PERUA', 'Perua / Station Wagon'), ('PICKUP', 'Pick-up / Caminhonete'), ('MINIVAN', 'Minivan'), ('VAN', 'Van de Carga ou Passageiros'), ('FURGAO', 'Furgão'), ('UTILITARIO', 'Utilitário Leve'), ('CAMINHAO', 'Caminhão'), ('ONIBUS', 'Ônibus / Micro-ônibus'), ('OFFROAD', 'Off-road / 4x4'), ('BUGGY', 'Buggy')], default='HATCH', max_length=30)),
                ('tipo_combustivel', models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('D', 'Diesel'), ('E', 'Elétrico'), ('H', 'Híbrido'), ('F', 'Flex')], default='G', max_length=1)),
                ('crlv', models.FileField(blank=True, null=True, upload_to='documentos/veiculos/crlv/')),
                ('seguro', models.FileField(blank=True, null=True, upload_to='documentos/veiculos/seguro/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motoristas', models.ManyToManyField(blank=True, related_name='veiculos', to='controle.motorista')),
            ],
        ),
    ]
