# Generated by Django 5.2.5 on 2025-08-31 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='categoria_cnh',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cnh',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='data_validade',
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/motoristas/cnh/'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh_categoria',
            field=models.CharField(choices=[('A', 'A - Moto'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus'), ('E', 'E - Carreta'), ('AB', 'AB - Moto e Carro')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh_numero',
            field=models.CharField(default='0', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh_validade',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status_atual',
            field=models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('MA', 'Em manutenção'), ('VE', 'Vendido')], default='AT', max_length=2),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_combustivel',
            field=models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('D', 'Diesel'), ('E', 'Elétrico'), ('H', 'Híbrido'), ('F', 'Flex')], default='F', max_length=1),
        ),
        migrations.CreateModel(
            name='HistoricoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('MA', 'Em manutenção'), ('VE', 'Vendido')], max_length=2)),
                ('km', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='controle.veiculo')),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='controle.setor'),
        ),
    ]
