# Generated by Django 5.2.5 on 2025-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_setor_remove_motorista_categoria_cnh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
