# Generated by Django 5.2.5 on 2025-08-31 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_motorista_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoveiculo',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data da alteração ou revisão'),
        ),
        migrations.AlterField(
            model_name='historicoveiculo',
            name='km',
            field=models.PositiveIntegerField(blank=True, help_text='Quilometragem da revisão', null=True),
        ),
        migrations.AlterField(
            model_name='historicoveiculo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre a revisão ou alteração de status', null=True),
        ),
    ]
