# Generated by Django 5.2.5 on 2025-08-31 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_alter_historicoveiculo_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.PositiveIntegerField(help_text='Quilometragem do veículo no momento da revisão')),
                ('tipo_manutencao', models.CharField(blank=True, help_text='Ex: Troca de óleo, Freios, Pneus, Revisão geral', max_length=50, null=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='controle.veiculo')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricoVeiculo',
        ),
    ]
