# Generated by Django 5.2.5 on 2025-08-31 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_manutencaoveiculo_delete_historicoveiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_infracao', models.DateField(default=django.utils.timezone.now, help_text='Data em que a infração ocorreu')),
                ('local', models.CharField(help_text='Local onde a infração foi registrada', max_length=200)),
                ('orgao_autuador', models.CharField(help_text='Órgão que aplicou a multa', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da multa em reais', max_digits=10)),
                ('natureza', models.CharField(help_text='Natureza da infração, ex: Estacionamento irregular, excesso de velocidade', max_length=100)),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Número de pontos na CNH referente à infração')),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/multas/')),
                ('data_registro', models.DateTimeField(auto_now_add=True, help_text='Data e hora do registro da multa no sistema')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='controle.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='controle.veiculo')),
            ],
        ),
    ]
