# Generated by Django 5.2.5 on 2025-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
    ]
