# Generated by Django 5.2.5 on 2025-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_veiculo_ano_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cnh_numero',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
