# Generated by Django 5.2.5 on 2025-08-31 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_alter_motorista_cnh_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/veiculos/termo/')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.veiculo')),
            ],
        ),
    ]
