# Generated by Django 5.2.5 on 2025-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_termoresponsabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termoresponsabilidade',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/veiculos/termo/'),
        ),
    ]
