# Generated by Django 5.2.5 on 2025-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0010_alter_termoresponsabilidade_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
