# Generated by Django 5.2.5 on 2025-09-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_alter_motorista_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(default=71981238230, max_length=15),
            preserve_default=False,
        ),
    ]
