# Generated by Django 5.2.5 on 2025-09-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0012_motorista_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(choices=[('BRANCO', 'Branco'), ('PRATA', 'Prata'), ('AZUL', 'Azul'), ('CINZA', 'Cinza'), ('VERMELHO', 'Vermelho'), ('PRETO', 'Preto'), ('AMARELO', 'Amarelo')], default='BRANCO', max_length=30),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_modelo',
            field=models.CharField(choices=[('HATCH', 'Hatch'), ('SEDAN', 'Sedã'), ('SUV', 'SUV'), ('CROSSOVER', 'Crossover'), ('COUPE', 'Coupé'), ('CONVERSIVEL', 'Conversível'), ('PERUA', 'Perua / Station Wagon'), ('PICKUP', 'Pick-up / Caminhonete'), ('MINIVAN', 'Minivan'), ('VAN', 'Van de Carga ou Passageiros'), ('FURGAO', 'Furgão'), ('UTILITARIO', 'Utilitário Leve'), ('CAMINHAO', 'Caminhão'), ('ONIBUS', 'Ônibus / Micro-ônibus'), ('OFFROAD', 'Off-road / 4x4'), ('BUGGY', 'Buggy'), ('MOTO', 'Moto')], default='HATCH', max_length=30),
        ),
    ]
