# Generated by Django 5.2.5 on 2025-09-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0013_veiculo_cor_alter_veiculo_tipo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo_frota',
            field=models.CharField(choices=[('PROPRIO', 'PROPRIO'), ('LOCADO', 'LOCADO')], default='PROPRIO', max_length=30),
        ),
    ]
