# Generated by Django 5.2.5 on 2025-09-14 19:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0014_veiculo_tipo_frota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVeiculo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=10)),
                ('renavam', models.CharField(db_index=True, max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('ano_modelo', models.PositiveIntegerField()),
                ('chassi', models.CharField(db_index=True, max_length=50)),
                ('tipo_frota', models.CharField(choices=[('PROPRIO', 'PROPRIO'), ('LOCADO', 'LOCADO')], default='PROPRIO', max_length=30)),
                ('cor', models.CharField(choices=[('BRANCO', 'Branco'), ('PRATA', 'Prata'), ('AZUL', 'Azul'), ('CINZA', 'Cinza'), ('VERMELHO', 'Vermelho'), ('PRETO', 'Preto'), ('AMARELO', 'Amarelo')], default='BRANCO', max_length=30)),
                ('tipo_modelo', models.CharField(choices=[('HATCH', 'Hatch'), ('SEDAN', 'Sedã'), ('SUV', 'SUV'), ('CROSSOVER', 'Crossover'), ('COUPE', 'Coupé'), ('CONVERSIVEL', 'Conversível'), ('PERUA', 'Perua / Station Wagon'), ('PICKUP', 'Pick-up / Caminhonete'), ('MINIVAN', 'Minivan'), ('VAN', 'Van de Carga ou Passageiros'), ('FURGAO', 'Furgão'), ('UTILITARIO', 'Utilitário Leve'), ('CAMINHAO', 'Caminhão'), ('ONIBUS', 'Ônibus / Micro-ônibus'), ('OFFROAD', 'Off-road / 4x4'), ('BUGGY', 'Buggy'), ('MOTO', 'Moto')], default='HATCH', max_length=30)),
                ('tipo_combustivel', models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('D', 'Diesel'), ('E', 'Elétrico'), ('H', 'Híbrido'), ('F', 'Flex')], default='F', max_length=1)),
                ('crlv', models.TextField(blank=True, max_length=100, null=True)),
                ('seguro', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status_atual', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('MA', 'Em manutenção'), ('VE', 'Vendido')], default='AT', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controle.setor')),
            ],
            options={
                'verbose_name': 'historical veiculo',
                'verbose_name_plural': 'historical veiculos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
