# Generated by Django 5.2.5 on 2025-09-14 20:09

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0015_historicalveiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMotorista',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(db_index=True, max_length=14)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('cnh_numero', models.CharField(db_index=True, max_length=20)),
                ('cnh_validade', models.DateField(default=django.utils.timezone.now)),
                ('cnh_categoria', models.CharField(choices=[('A', 'A - Moto'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus'), ('E', 'E - Carreta'), ('AB', 'AB - Moto e Carro')], default='B', max_length=2)),
                ('cnh_arquivo', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical motorista',
                'verbose_name_plural': 'historical motoristas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
