# Generated by Django 5.2.5 on 2025-09-16 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0017_historicalveiculo_created_by_veiculo_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmotorista',
            name='data_nacimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicalmotorista',
            name='status_atual',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7),
        ),
        migrations.AddField(
            model_name='motorista',
            name='data_nacimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='motorista',
            name='status_atual',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalmotorista',
            name='cnh_categoria',
            field=models.CharField(choices=[('A', 'A - Moto'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus'), ('E', 'E - Carreta'), ('AB', 'AB - Moto e Carro'), ('AD', 'AD - Caminhão e Carro'), ('AE', 'AE - Caminhão com reboque e Carro')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh_categoria',
            field=models.CharField(choices=[('A', 'A - Moto'), ('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus'), ('E', 'E - Carreta'), ('AB', 'AB - Moto e Carro'), ('AD', 'AD - Caminhão e Carro'), ('AE', 'AE - Caminhão com reboque e Carro')], default='B', max_length=2),
        ),
    ]
