# Generated by Django 5.2.5 on 2025-09-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0018_historicalmotorista_data_nacimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmotorista',
            name='telefone',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(max_length=16),
        ),
    ]
