# Generated by Django 5.2.5 on 2025-09-17 13:55

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0020_historicaltermoresponsabilidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfracaoTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('gravidade', models.CharField(choices=[('leve', 'Leve'), ('media', 'Média'), ('grave', 'Grave'), ('gravissima', 'Gravíssima')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='multa',
            name='natureza',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='pontos',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='valor',
        ),
        migrations.AddField(
            model_name='multa',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, help_text='Comprovante de pagamento', null=True, upload_to='documentos/multas/comprovantes/'),
        ),
        migrations.AddField(
            model_name='multa',
            name='documento_recebido',
            field=models.FileField(blank=True, help_text='Documento com carimbo de recebido', null=True, upload_to='documentos/multas/recebidos/'),
        ),
        migrations.AddField(
            model_name='multa',
            name='prazo_pagamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='multa',
            name='setor',
            field=models.CharField(blank=True, help_text='Setor do veículo no momento da infração', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='status_multa',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('recebido', 'Recebido')], default='enviado', max_length=20),
        ),
        migrations.AddField(
            model_name='multa',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='multa',
            name='data_infracao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='multa',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='local',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multa',
            name='orgao_autuador',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='HistoricalMulta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('setor', models.CharField(blank=True, help_text='Setor do veículo no momento da infração', max_length=100, null=True)),
                ('data_infracao', models.DateField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=200)),
                ('orgao_autuador', models.CharField(max_length=100)),
                ('prazo_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('status_multa', models.CharField(choices=[('enviado', 'Enviado'), ('recebido', 'Recebido')], default='enviado', max_length=20)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('documento_recebido', models.TextField(blank=True, help_text='Documento com carimbo de recebido', max_length=100, null=True)),
                ('comprovante_pagamento', models.TextField(blank=True, help_text='Comprovante de pagamento', max_length=100, null=True)),
                ('documento', models.TextField(blank=True, max_length=100, null=True)),
                ('data_registro', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controle.motorista')),
                ('veiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controle.veiculo')),
                ('infracao', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de infração cometida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controle.infracaotransito')),
            ],
            options={
                'verbose_name': 'historical multa',
                'verbose_name_plural': 'historical multas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='multa',
            name='infracao',
            field=models.ForeignKey(blank=True, help_text='Tipo de infração cometida', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='controle.infracaotransito'),
        ),
    ]
