# Generated by Django 5.2.5 on 2025-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0021_infracaotransito_remove_multa_natureza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmulta',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='documento',
        ),
        migrations.AddField(
            model_name='historicalmulta',
            name='memorando',
            field=models.TextField(blank=True, help_text='Memorando criado por FleetManager', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmulta',
            name='notificacao_infracao',
            field=models.TextField(blank=True, help_text='Notificao recebida do orgao atuador', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmulta',
            name='numero_memorando',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='memorando',
            field=models.FileField(blank=True, help_text='Memorando criado por FleetManager', null=True, upload_to='documentos/multas/memorandos/'),
        ),
        migrations.AddField(
            model_name='multa',
            name='notificacao_infracao',
            field=models.FileField(blank=True, help_text='Notificao recebida do orgao atuador', null=True, upload_to='documentos/multas/'),
        ),
        migrations.AddField(
            model_name='multa',
            name='numero_memorando',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
