# Generated by Django 5.2.5 on 2025-09-17 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0022_remove_historicalmulta_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmulta',
            name='data_infracao',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='data_infracao',
        ),
        migrations.AddField(
            model_name='historicalmulta',
            name='Auto_Infracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmulta',
            name='data_hora_infracao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='multa',
            name='Auto_Infracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='data_hora_infracao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
