# Generated by Django 5.2.5 on 2025-09-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0023_remove_historicalmulta_data_infracao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmulta',
            old_name='Auto_Infracao',
            new_name='auto_infracao',
        ),
        migrations.RenameField(
            model_name='multa',
            old_name='Auto_Infracao',
            new_name='auto_infracao',
        ),
    ]
