# Generated by Django 5.2.5 on 2025-09-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0024_rename_auto_infracao_historicalmulta_auto_infracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(help_text='Nome do banco, ex: Banco do Brasil', max_length=100)),
                ('agencia', models.CharField(help_text='Número da agência, ex: 0000', max_length=10)),
                ('conta_corrente', models.CharField(help_text='Número da conta corrente, ex: 000000-0', max_length=20)),
                ('favorecido', models.CharField(default='Prefeitura Municipal de Lauro de Freitas – Secretaria de Administração', help_text='Nome do favorecido', max_length=200)),
                ('cnpj', models.CharField(help_text='CNPJ do favorecido, ex: XX.XXX.XXX/0001-XX', max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='historicalmulta',
            name='conta_pagamento',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Conta para pagamento da multa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controle.contapagamento'),
        ),
        migrations.AddField(
            model_name='multa',
            name='conta_pagamento',
            field=models.ForeignKey(blank=True, help_text='Conta para pagamento da multa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='controle.contapagamento'),
        ),
    ]
