# Generated by Django 5.2.5 on 2025-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0025_contapagamento_historicalmulta_conta_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmulta',
            name='auto_infracao',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='auto_infracao',
            field=models.CharField(blank=True, null=True),
        ),
    ]
