# Generated by Django 5.2.5 on 2025-09-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0026_alter_historicalmulta_auto_infracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmulta',
            name='setor_descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='multa',
            name='setor_descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
