# Generated by Django 5.2.5 on 2025-10-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0027_historicalmulta_setor_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hodometro', models.PositiveIntegerField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_litro', models.DecimalField(decimal_places=2, editable=False, max_digits=7)),
                ('posto', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abastecido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='controle.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='controle.veiculo')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
