# Generated by Django 5.2.5 on 2025-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0028_abastecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalveiculo',
            name='hodometro',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quilometragem atual do veículo', null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='hodometro',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quilometragem atual do veículo', null=True),
        ),
    ]
