# Generated by Django 5.2.5 on 2025-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0029_historicalveiculo_hodometro_veiculo_hodometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='tipo_combustivel',
            field=models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('D', 'Diesel'), ('E', 'Elétrico'), ('H', 'Híbrido'), ('F', 'Flex')], default='F', help_text='Tipo de combustível abastecido', max_length=1),
        ),
    ]
